<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card">
    <dl class="row">
        <dt class="col-sm-5">European river code</dt>
        <dd class="col-sm-7"><?=$record['european_river_code'] ?? '';?></dd>
        <dt class="col-sm-5">Cname</dt>
        <dd class="col-sm-7"><?=$record['cname'] ?? '';?></dd>

    </dl>
</div>
<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
