<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card showPage">
	<div class="actions">
		<a href="/admin/hydro/waterbodies/edit?id=<?=$record['european_river_code'];?>" class="btn btn-primary">Edit waterbody</a>
		<a href="<?=$listPage;?>" class="btn btn-secondary">Back to list</a>
	</div>

	<h1>Waterbody #<?=$record['european_river_code'] ?? '';?></h1>

	<dl class="row">
        <dt class="col-sm-5">European river code</dt>
        <dd class="col-sm-7"><?=$record['european_river_code'] ?? '';?></dd>
        <dt class="col-sm-5">Cname</dt>
        <dd class="col-sm-7"><?=$record['cname'] ?? '';?></dd>

    </dl>
</div>
<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
