<?php include __DIR__ . '/../layouts/before_app.phtml'; ?>
<?php $editMode = isset($record) && !empty($record['id']); ?>

<div class="card formPage">
	<?=includeTemplatePart('crud_show_header.phtml', get_defined_vars());?>
	<form method="post">
		<input type="hidden" name="__csrf" value="<?=$csrf;?>"/>

		<div class="mb-3">
			<label for="userName" class="form-label"><?=__('Name');?></label>
			<input type="text" name="name" id="userName" class="form-control <?=isFieldInvalidClass('name', get_defined_vars());?>" value="<?=formFieldValue('name', $record);?>" />
			<div class="invalid-feedback">
				<?=getFieldInvalidMessage('name', get_defined_vars());?>
			</div>
		</div>
		<div class="mb-3">
			<label for="userEmail" class="form-label"><?=__('E-mail');?></label>
			<input type="text" name="email" id="userEmail" class="form-control <?=isFieldInvalidClass('email', get_defined_vars());?>" value="<?=formFieldValue('email', $record);?>" />
			<div class="invalid-feedback">
				<?=getFieldInvalidMessage('email', get_defined_vars());?>
			</div>
		</div>
		<?php if (!$editMode): ?>
		<div class="mb-3">
			<label for="operatorUsername" class="form-label"><?=__('Username')?></label>
			<input type="text" name="username" id="operatorUsername" class="form-control <?=isFieldInvalidClass('username', get_defined_vars());?>" value="<?=formFieldValue('username', $record);?>" />
			<div class="invalid-feedback">
				<?=getFieldInvalidMessage('username', get_defined_vars());?>
			</div>
		</div>
		<?php endif; ?>
		<div class="mb-3">
			<label for="userPassword" class="form-label"><?=$editMode ? 'New password' : 'Password';?></label>
			<input type="password" name="password" id="userPassword" class="form-control <?=isFieldInvalidClass('password', get_defined_vars());?>"  />
			<div class="invalid-feedback">
				<?=getFieldInvalidMessage('password', get_defined_vars());?>
			</div>
		</div>
		<?php if ($editMode): ?>
		<div class="mb-3">
			<label for="userPasswordConfirm" class="form-label"><?='New password confirm';?></label>
			<input type="password" name="password_confirm" id="userPasswordConfirm" class="form-control <?=isFieldInvalidClass('password_confirm', get_defined_vars());?>"  />
			<div class="invalid-feedback">
				<?=getFieldInvalidMessage('password_confirm', get_defined_vars());?>
			</div>
		</div>
		<?php endif; ?>
		<div class="mb-3">
			<label for="publicKey" class="form-label"><?=$editMode ? 'Set new public key' : 'Public key';?></label>
			<textarea name="public_key" id="publicKey" class="form-control"><?=formFieldValue('public_key', $record);?></textarea>
		</div>

		<fieldset class="mb-3">
			<legend><?=__('Permissions');?></legend>
			<?php $selectedPermissions = array_filter(formFieldValue('form_permissions', $record) ?: []); ?>
			<?php for($i = 0; $i <= count($selectedPermissions); $i++) { ?>
				<div class="field">
					<select name="form_permissions[]" class="form-select">
						<?=selectOptions($permissions, $selectedPermissions[$i] ?? null, ' - '.__('No permission').' - ');?>
					</select>
				</div>
			<?php } ?>
		</fieldset>

		<fieldset class="mb-3">
			<legend><?=__('Groups');?></legend>
			<?php $selectedGroups = array_filter(formFieldValue('form_groups', $record) ?: []); ?>
			<?php for($i = 0; $i <= count($selectedGroups); $i++) { ?>
				<div class="field">
					<select name="form_groups[]" class="form-select">
						<?=selectOptions($groups, $selectedGroups[$i] ?? null, ' - '.__('No groups').' - ');?>
					</select>
				</div>
			<?php } ?>
		</fieldset>

		<div class="field">
			<input type="submit" class="btn btn-primary" value="<?=__('Save');?>"/>
		</div>
	</form>
</div>
<?php include __DIR__ . '/../layouts/after_app.phtml'; ?>
