<?php include __DIR__ . '../../layouts/before_app.phtml'; ?>

<div class="card">

	<div class="d-flex w-100">
		<div class="mr-auto form-group">
			<a href="/admin/users/add" class="btn btn-primary">Add user</a>
		</div>
		<div class="form-group">
			<form method="get">
				<input type="search" name="search" class="form-control" placeholder="<?=__('Search')?>" value="<?=htmlspecialchars(urldecode($searchString))?>">
			</form>
		</div>
	</div>

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th><?=sortableColumn('Name', 'name');?></th>
                <th><?=sortableColumn('Username', 'username');?></th>
                <th><?=sortableColumn('E-mail address', 'email');?></th>
                <th><?=sortableColumn('Last login', 'loggedin_at');?></th>
                <th>Groups</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php
				if (count($records) > 0):
					foreach ($records as $user):
			?>
                <tr>
                    <td><?=$user['name'] ?? null;?></td>
                    <td><?=$user['username'] ?? null;?></td>
                    <td><?=$user['email'] ?? null;?></td>
                    <td><?=($user['loggedin_at'] ? (new DateTime($user['loggedin_at']))->format('Y-m-d H:i:s') : '');?></td>
                    <td><?=$user['group_names'] ?? null;?></td>
                    <td class="actions">
                        <a href="/admin/users/show?id=<?=$user['id'];?>"><i class="fas fa-eye text-muted"></i></a>
                        <a href="/admin/users/edit?id=<?=$user['id'];?>"><i class="fas fa-edit"></i></a>
                        <a href="/admin/users/delete?id=<?=$user['id'];?>" onclick="return confirm('Are you sure to delete?')"><i class="fas fa-trash text-danger"></i></a>
                    </td>
                </tr>
            <?php
					endforeach;
				else:
			?>
				<tr>
					<td colspan="6">
						There is no record to show.
					</td>
				</tr>
			<?
				endif;
			?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="6">
                    <div class="paginator">
                        <?php include __DIR__.'/../parts/paginator.phtml';?>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
<?php include __DIR__ . '../../layouts/after_app.phtml'; ?>
