<?php include __DIR__ . '../../layouts/before_app.phtml'; ?>
<div class="card showPage">
	<div class="actions">
		<a href="/admin/users/edit?id=<?=$record['id'];?>" class="btn btn-primary">Edit user</a>
		<a href="<?=$listPage;?>" class="btn btn-secondary">Back to list</a>
	</div>

	<h1>User #<?=$record['id'] ?? '';?></h1>

    <dl class="row">
        <dt class="col-sm-3">ID</dt>
        <dd class="col-sm-9">#<?=$record['id'] ?? '';?></dd>
        <dt class="col-sm-3">Name</dt>
        <dd class="col-sm-9"><?=$record['name'] ?? '';?></dd>
        <dt class="col-sm-3">Username</dt>
        <dd class="col-sm-9"><?=$record['username'] ?? '';?></dd>
        <dt class="col-sm-3">E-mail address</dt>
        <dd class="col-sm-9"><?=$record['email'] ?? '';?></dd>
        <dt class="col-sm-3">Last login at</dt>
        <dd class="col-sm-9"><?=dateFormat($record['loggedin_at'] ?? null)?></dd>
        <dt class="col-sm-3">Groups</dt>
        <dd class="col-sm-9">
            <ul>
                <?php foreach ($record['show_groups'] ?: [] as $group) { ?>
                    <li>
                        <a href="/admin/groups/show?id=<?=$group['id'];?>">#<?=$group['id'] ?? null;?></a>
                        -
                        <span><?=$group['name'] ?? null;?></span>
                    </li>
                <?php } ?>
            </ul>
        </dd>
        <dt class="col-sm-3">Operators</dt>
        <dd class="col-sm-9">
            <ul>
                <?php foreach ($record['show_operators'] ?: [] as $operator) { ?>
                    <li>
                        <a href="/admin/operators/show?id=<?=$operator['id'];?>">#<?=$operator['id'] ?? null;?></a>
                        -
                        <span><?=$operator['name'] ?? null;?> (<?=userGroupConnectionType($operator['connection_type']);?>)</span>
                    </li>
                <?php } ?>
            </ul>
        </dd>
        <dt class="col-sm-3">Public keys</dt>
        <dd class="col-sm-9">
			<?php foreach ($record['show_publicKeys'] ?: [] as $publicKey) { ?>
				<pre class="small"><?=$publicKey['public_key'];?></pre>
			<?php } ?>
        </dd>
    </dl>
</div>

<?php include __DIR__ . '../../layouts/after_app.phtml'; ?>
