<?php include 'layouts/before_app.phtml'; ?>

	<?php if($response) {?>
	<div>
		Status: <?=$response->getStatusCode();?><br />
		Body: <pre><?=$response->getBody();?></pre>
	</div>
	<?php } ?>

	<?php if($error) {?>
	<div>Error: <?=$error;?></div>
	<?php } ?>

	<hr>

	<form id="uploadTestForm" action="" method="POST">
		<?php include __DIR__.'/parts/messages.phtml'; //Render flash messages?>
		<h1><?=__('Test download with filters');?></h1>
		<div class="form-group">
			<label for="country"><?=__('Available countries');?>: </label>
			<select name="country[]" id="country" multiple>
				<?=selectOptions($countries, formFieldValue('country'));?>
			</select>
		</div>
		<div class="form-group">
			<label for="symbol"><?=__('Available observed property symbols');?>: </label>
			<select name="symbol[]" id="symbol" multiple>
				<?=selectOptions($symbols, formFieldValue('symbol'));?>
			</select>
		</div>
		<div class="form-group">
			<label for="username"><?=__('User');?></label>
			<select name="username" id="username">
				<?=selectOptions($users, formFieldValue('username'));?>
			</select>
		</div>
		<div class="form-group">
			<label for="start"><?=__('Start time');?></label><br />
			<input type="datetime-local" name="start" id="start">
		</div>
		<div class="form-group">
			<label for="end"><?=__('End time');?></label><br />
			<input type="datetime-local" name="end" id="end">
		</div>
		<input type="hidden" name="__csrf" value="<?=$csrf;?>"/>
		<input type="submit" class="btn btn-primary" value="Send">
	</form>

<?php include 'layouts/after_app.phtml'; ?>