<?php include 'layouts/before_app.phtml'; ?>

<div class="card">
	<h1>Upload processed data</h1>
	<p><small>You can download a sample CSV file from <a href="/samples/processed_data.csv" target="_blank">here</a></small></p>
	<form id="processedDataForm" action="" method="POST" enctype="multipart/form-data">

		<div class="form-group">
			<label for="mpoint"><?=sprintf(__('CSV files'));?></label>
			<input type="file" name="csv[]" multiple />
			<br />
			<small id="passwordHelpBlock" class="form-text text-muted">
				You can upload maximum <?=$maxFiles;?> files. <br />
				Maximal cumulate size of uploaded files: <?=$maxSize;?>
			</small>
		</div>
		<input type="hidden" name="__csrf" value="<?=$csrf;?>"/>
		<input type="submit" class="btn btn-primary" value="Send">
	</form>
</div>

<?php include 'layouts/after_app.phtml'; ?>