<?php use Environet\Sys\Upload\Statistics;

include 'layouts/before_app.phtml'; ?>

	<div class="card">
		<h1>Upload processed or missing data - Step 2</h1>
		<p>The uploaded files have been preprocessed, but not yet updated. Please confirm the changes, and press "Confirm" button.</p>
		<form id="uploadDataForm" action="" method="POST" enctype="multipart/form-data">
			<div class="uploadStatistics">
				<?php foreach ($fileResponses as $originalFileName => $fileResponse) { ?>
					<ul class="list-group">
						<li class="list-group-item">
							<h3><?=$originalFileName;?></h3>
							<?php if ($fileResponse instanceof Statistics) { ?>
								<input type="hidden" name="xml_file[xml][]" value="<?=$fileResponse->getInputXmlFile();?>" />
								<input type="hidden" name="xml_file[original][]" value="<?=$originalFileName;?>" />
								<ul>
									<li><strong>Count of uploaded properties</strong>: <?=$fileResponse->getInputPropertiesCount();?></li>
									<?php foreach ($fileResponse->getProperties() as $propertySymbol) { ?>
										<li><strong>Property</strong>: <?=$propertySymbol;?></li>
										<ul>
											<li><strong>Inserts </strong>: <?=$fileResponse->getPropertyInserts($propertySymbol);?></li>
											<li><strong>Updates </strong>: <?=$fileResponse->getPropertyUpdates($propertySymbol);?></li>
											<li><strong>No changes </strong>: <?=$fileResponse->getPropertyNoChanges($propertySymbol);?></li>
										</ul>
									<?php } ?>
								</ul>
							<?php } elseif (is_array($fileResponse)) { ?>
								<?php foreach ($fileResponse as $message) { ?>
									<div class="alert alert-danger" role="alert">
										<?=$message;?>
									</div>
								<?php } ?>
							<?php } ?>
						</li>
					</ul>
				<?php } ?>
			</div>
			<input type="hidden" name="__csrf" value="<?=$csrf;?>"/>
			<input type="submit" class="btn btn-primary" value="Confirm">
		</form>

	</div>
	<div class="card mt-3">
		<h2>Upload other files</h2>
		<?php include 'upload_data_form.phtml'; ?>
	</div>

<?php include 'layouts/after_app.phtml'; ?>