<?php
/**
 * @var UploadFileResponse $fileResponse
 */
use Environet\Sys\Upload\Statistics;
use Environet\Sys\Upload\UploadFileResponse;

include 'layouts/before_app.phtml'; ?>

	<div class="card">
		<h1>Upload processed or missing data - Step 2</h1>
		<?php if ($hasErrors) { ?>
			<p>The uploaded files have been preprocessed, but validation failed. Please check the errors, and try again!</p>
		<?php } else { ?>
			<p>The uploaded files have been validated, but not yet imported. Please review the changes listed below and press the "Confirm" button to import the data.</p>
		<?php } ?>
		<form id="uploadDataForm" action="" method="POST" enctype="multipart/form-data">
			<div class="uploadStatistics">
				<?php foreach ($fileResponses as $fileResponse) { ?>
					<ul class="list-group">
						<li class="list-group-item">
							<h3><?=$fileResponse->getOriginalFileName();?></h3>
							<?php if ($fileResponse->hasErrors()) { ?>
								<?php foreach ($fileResponse->getErrorMessages() as $message) { ?>
									<div class="alert alert-danger" role="alert">
										<?=$message;?>
									</div>
								<?php } ?>
								<?php foreach ($fileResponse->getWarningMessages() as $message) { ?>
									<div class="alert alert-warning" role="alert">
										<?=$message;?>
									</div>
								<?php } ?>
							<?php } else { ?>
								<?php foreach ($fileResponse->getSuccessMessages() as $message) { ?>
									<div class="alert alert-success" role="alert">
										<?=$message;?>
									</div>
								<?php } ?>
								<?php foreach ($fileResponse->getWarningMessages() as $message) { ?>
									<div class="alert alert-warning" role="alert">
										<?=$message;?>
									</div>
								<?php } ?>
								<?php if (!empty($fileResponse->getStatistics()->hasDuplicatePointTimes())) { ?>
									<div class="alert alert-warning" role="alert">
										<strong>Warning!</strong> The uploaded file contains multiple values for the same time. You can check the affected times below.
										<br />
										If you confirm the upload, the last value will be used for the given time, everything else will be imported as obsolete values.
									</div>
								<?php } ?>

								<input type="hidden" name="xml_file[xml][]" value="<?=$fileResponse->getStatistics()->getInputXmlFile();?>" />
								<input type="hidden" name="xml_file[original][]" value="<?=$fileResponse->getOriginalFileName();?>" />
								<ul>
									<li><strong>Monitoring point</strong>: <?=$fileResponse->getStatistics()->getMonitoringPointId();?></li>
									<li><strong>Count of uploaded properties</strong>: <?=$fileResponse->getStatistics()->getInputPropertiesCount();?></li>
									<?php foreach ($fileResponse->getStatistics()->getProperties() as $propertySymbol) { ?>
										<li><strong>Property</strong>: <?=$propertySymbol;?></li>
										<ul>
											<li><strong>Inserts </strong>: <?=$fileResponse->getStatistics()->getPropertyInserts($propertySymbol);?></li>
											<li><strong>Updates </strong>: <?=$fileResponse->getStatistics()->getPropertyUpdates($propertySymbol);?></li>
											<?php if ($fileResponse->getStatistics()->getDuplicatePointTimes($propertySymbol)) { ?>
												<li>
													<strong>Duplicate times </strong>:
													<ul>
														<?php foreach ($fileResponse->getStatistics()->getDuplicatePointTimes($propertySymbol) as $duplicatePointTime) { ?>
															<li><?=$duplicatePointTime;?></li>
														<?php } ?>
													</ul>
												</li>
											<?php } ?>
											<li><strong>No changes </strong>: <?=$fileResponse->getStatistics()->getPropertyNoChanges($propertySymbol);?></li>
											<li><strong>Minimum result time </strong>: <?=$fileResponse->getStatistics()->getPropertyMinTimeFormatted($propertySymbol);?></li>
											<li><strong>Maximum result time </strong>: <?=$fileResponse->getStatistics()->getPropertyMaxTimeFormatted($propertySymbol);?></li>
										</ul>
									<?php } ?>
								</ul>
							<?php } ?>
						</li>
					</ul>
				<?php } ?>
			</div>
			<input type="hidden" name="__csrf" value="<?=$csrf;?>" />

			<?php if (!$hasErrors) { ?>
				<input type="submit" class="btn btn-primary oneClickSubmit" data-processingvalue="Upload is in progress..." value="Confirm">
			<?php } ?>
		</form>

	</div>

	<div class="card mt-3">
		<h2>Upload files again</h2>
		<?php include 'upload_data_form.phtml'; ?>
	</div>


<?php include 'layouts/after_app.phtml'; ?>