<?php include __DIR__ . '../../layouts/before_app.phtml'; ?>

<div class="card formPage">
	<div class="actions">
		<a href="<?=$listPage;?>" class="btn btn-secondary">Back to list</a>
	</div>
	<h1><?= __(($record && $record['id']) ? 'Edit operator #' . $record['id'] : 'Add operator and it\'s user'); ?></h1>
	<form action="" method="POST">
		<input type="hidden" name="__csrf" value="<?=$csrf;?>"/>

		<fieldset>
			<legend><?=__('Operator data');?></legend>
			<div class="form-group">
				<label for="dataProviderName"><?=__('Name');?></label>
				<input type="text" name="name" id="dataProviderName" class="form-control" value="<?=formFieldValue('name', $record);?>" />
			</div>
			<div class="form-group">
				<label for="dataProviderAddress"><?=__('Address');?></label>
				<textarea name="address" id="dataProviderAddress" class="form-control"><?=formFieldValue('address', $record);?></textarea>
			</div>
			<div class="form-group">
				<label for="dataProviderPhone"><?=__('Phone');?></label>
				<input type="tel" name="phone" id="dataProviderPhone" class="form-control" value="<?=formFieldValue('phone', $record);?>" />
			</div>
			<div class="form-group">
				<label for="dataProviderEmail"><?=__('E-mail');?></label>
				<input type="email" name="email" id="dataProviderEmail" class="form-control" value="<?=formFieldValue('email', $record);?>" />
			</div>
			<div class="form-group">
				<label for="dataProviderUrl"><?=__('URL');?></label>
				<input type="url" name="url" id="dataProviderUrl" class="form-control" value="<?=formFieldValue('url', $record);?>"/>
				<small class="help-block text-muted">Full url, e.g. https://example.com</small>
			</div>
			<div class="form-group">
				<label for="dataProviderOtherInfo"><?=__('Other info');?></label>
				<input type="text" name="other_info" id="dataProviderOtherInfo" class="form-control" value="<?=formFieldValue('other_info', $record);?>" />
			</div>
		</fieldset>

		<?php if ($record && $record['id']): ?>
            <fieldset class="form-group">
                <legend><?=__('Users');?></legend>
                <?php $selectedUsers = array_filter(formFieldValue('form_users', $record) ?: []); ?>
                <?php for($i = 0; $i <= count($selectedUsers); $i++) { ?>
                    <div class="field">
                        <select name="form_users[]">
                            <?=selectOptions($users, $selectedUsers[$i] ?? null, ' - '.__('No user').' - ');?>
                        </select>
                    </div>
                <?php } ?>
            </fieldset>

            <fieldset class="form-group">
                <legend><?=__('Groups');?></legend>
                <?php $selectedGroups = array_filter(formFieldValue('form_groups', $record) ?: []); ?>
                <?php for($i = 0; $i <= count($selectedGroups); $i++) { ?>
                    <div class="field">
                        <select name="form_groups[]">
                            <?=selectOptions($groups, $selectedGroups[$i] ?? null, ' - '.__('No group').' - ');?>
                        </select>
                    </div>
                <?php } ?>
            </fieldset>
		<?php else: ?>
			<fieldset>
				<legend>User data</legend>
				<div class="form-group">
					<label for="dataProviderName">Name</label>
					<input type="text" name="user_name" id="dataProviderName" class="form-control"  value="<?=$_POST['user_name'] ?? null;?>" />
				</div>
				<div class="form-group">
					<label for="dataProviderEmail">E-mail</label>
					<input type="email" name="user_email" id="dataProviderEmail" class="form-control"  value="<?=$_POST['user_email'] ?? null;?>" />
				</div>
				<div class="form-group">
					<label for="dataProviderUsername">Username</label>
					<input type="text" name="user_username" id="dataProviderUsername" class="form-control"  value="<?=$_POST['user_username'] ?? null;?>" />
				</div>
				<div class="form-group">
					<label for="dataProviderPassword">Password</label>
					<input type="password" name="user_password" id="dataProviderPassword" class="form-control"  />
				</div>
				<div class="form-group">
					<label for="dataProviderPublicKey">Public key</label>
					<textarea name="public_key" id="dataProviderPublicKey" class="form-control" ><?=$_POST['public_key'] ?? null;?></textarea>
				</div>
			</fieldset>
		<?php endif; ?>


		<div class="field">
			<input type="submit" class="btn btn-primary" value="<?=__('Save');?>"/>
		</div>


	</form>
</div>
<?php include __DIR__ . '../../layouts/after_app.phtml'; ?>
