<?php include __DIR__ . '../../layouts/before_app.phtml'; ?>
<div class="card">

	<div class="d-flex w-100">
		<div class="mr-auto form-group">
			<a href="/admin/data-providers/add" class="btn btn-primary" >Add data provider</a>
		</div>
		<div class="form-group">
			<form method="get">
				<input type="search" name="search" class="form-control" placeholder="<?=__('Search')?>" value="<?=htmlspecialchars(urldecode($searchString))?>">
			</form>
		</div>
	</div>

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th><?=sortableColumn('Operator name', 'name');?></th>
                <th><?=sortableColumn('User count', 'user_count');?></th>
                <th><?=sortableColumn('Group count', 'group_count');?></th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php
				if (count($operators) > 0):
					foreach ($operators as $operator):
			?>
                <tr>
                    <td><?=$operator['name'] ?? null;?></td>
                    <td><?=$operator['user_count'] ?? null;?></td>
                    <td><?=$operator['group_count'] ?? null;?></td>
                    <td class="actions">
                        <a href="/admin/data-providers/show?id=<?=$operator['id'];?>"><i class="fas fa-eye text-muted"></i></a>
                        <a href="/admin/data-providers/edit?id=<?=$operator['id'];?>"><i class="fas fa-edit"></i></a>
                    </td>
                </tr>
			<?php
					endforeach;
				else:
			?>
					<tr>
						<td colspan="4">
							There is no record to show.
						</td>
					</tr>
			<?
				endif;
            ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">
                    <div class="paginator">
                        <?php include __DIR__.'/../parts/paginator.phtml';?>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
<?php include __DIR__ . '../../layouts/after_app.phtml'; ?>
