<?php include __DIR__ . '../../layouts/before_app.phtml'; ?>
<div class="card">
    <dl class="row">
        <dt class="col-sm-3">ID</dt>
        <dd class="col-sm-9">#<?=$record['id'] ?? '';?></dd>
        <dt class="col-sm-3">Name</dt>
        <dd class="col-sm-9"><?=$record['name'] ?? '';?></dd>
        <dt class="col-sm-3">Address</dt>
        <dd class="col-sm-9"><?=$record['address'] ?? '';?></dd>
        <dt class="col-sm-3">E-mail address</dt>
        <dd class="col-sm-9"><?=$record['email'] ?? '';?></dd>
        <dt class="col-sm-3">Phone</dt>
        <dd class="col-sm-9"><?=$record['phone'] ?? '';?></dd>
        <dt class="col-sm-3">URL</dt>
        <dd class="col-sm-9"><?=$record['url'] ?? '';?></dd>
        <dt class="col-sm-3">Groups</dt>
        <dd class="col-sm-9">
            <ul>
            <?php foreach ($record['merged_groups'] ?: [] as $group) { ?>
                <li>
                    <a href="/admin/groups/show?id=<?=$group['id'];?>">#<?=$group['id'] ?? null;?></a>
                    -
                    <span><?=$group['name'] ?? null;?></span>
                </li>
            <?php } ?>
            </ul>
        </dd>
        <dt class="col-sm-3">Users</dt>
        <dd class="col-sm-9">
            <ul>
            <?php foreach ($record['merged_users'] ?: [] as $user) { ?>
                <li>
                    <a href="/admin/users/show?id=<?=$user['id'];?>">#<?=$user['id'] ?? null;?></a>
                     -
                    <span><?=$user['name'] ?? null;?> (<?=userGroupConnectionType($user['connection_type']);?>)</span>
                </li>
            <?php } ?>
            </ul>
        </dd>
    </dl>
</div>
<?php include __DIR__ . '../../layouts/after_app.phtml'; ?>
