<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card showPage">
	<?=includeTemplatePart('crud_show_header.phtml', get_defined_vars() + [
		'editUrl' => '/admin/hydro/rivers/edit?id='.$record['id']
	]);?>

	<dl class="row">
        <dt class="col-sm-5">International code of the river</dt>
        <dd class="col-sm-7"><?=$record['eucd_riv'] ?? '';?></dd>
        <dt class="col-sm-5">Name</dt>
        <dd class="col-sm-7"><?=$record['cname'] ?? '';?></dd>

    </dl>
</div>
<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
