<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card formPage">
	<?=includeTemplatePart('crud_show_header.phtml', get_defined_vars());?>
	<form action="" method="POST">
		<input type="hidden" name="__csrf" value="<?=$csrf;?>"/>
        <div class="form-group">
            <label for="symbol">Symbol</label>
            <input type="text" name="symbol" id="symbol" class="form-control"  value="<?=formFieldValue('symbol', $record);?>" />
        </div>

        <div class="form-group">
            <label for="unit">Unit</label>
            <input type="text" name="unit" id="unit" class="form-control"  value="<?=formFieldValue('unit', $record);?>" />
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" name="description" id="description" class="form-control"  value="<?=formFieldValue('description', $record);?>" />
        </div>

		<fieldset class="form-group">
			<legend>Type</legend>
			<div class="field">
				<select name="type">
					<?=selectOptions(observedPropertyTypeOptions(), formFieldValue('type', $record));?>
				</select>
			</div>
		</fieldset>

        <div class="field">
            <input type="submit" class="btn btn-primary" value="Save"/>
        </div>
    </form>
</div>

<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
