<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card">
    <h1>Meteo observed property</h1>
    <dl class="row">
        <dt class="col-sm-3">ID</dt>
        <dd class="col-sm-9">#<?=$record['id'] ?? '';?></dd>
        <dt class="col-sm-3">Symbol</dt>
        <dd class="col-sm-9"><?=$record['symbol'] ?? '';?></dd>
        <dt class="col-sm-3">Description</dt>
        <dd class="col-sm-9"><?=$record['description'] ?? '';?></dd>
        <dt class="col-sm-3">Type</dt>
        <dd class="col-sm-9"><?=$record['type'] ?? '';?></dd>

    </dl>
</div>
<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
