<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card showPage">
	<?=includeTemplatePart('crud_show_header.phtml', get_defined_vars() + [
		'editUrl' => '/admin/meteo/observed-properties/edit?id='.$record['id']
	]);?>
    <dl class="row">
        <dt class="col-sm-3">ID</dt>
        <dd class="col-sm-9">#<?=$record['id'] ?? '';?></dd>
        <dt class="col-sm-3">Symbol</dt>
        <dd class="col-sm-9"><?=$record['symbol'] ?? '';?></dd>
        <dt class="col-sm-3">Description</dt>
        <dd class="col-sm-9"><?=$record['description'] ?? '';?></dd>
        <dt class="col-sm-3">Type</dt>
        <dd class="col-sm-9"><?=observedPropertyTypeOptions()[$record['type']] ?? null;?></dd>

    </dl>
</div>
<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
