<?php include __DIR__ . '../../layouts/before_app.phtml'; ?>

	<div class="card">
		<h1><?= __(($record && $record['id']) ? 'Edit group (id: ' . $record['id'] . ')': 'Add group'); ?></h1>
		<form action="" method="POST">
			<input type="hidden" name="__csrf" value="<?=$csrf;?>"/>

			<div class="form-group">
				<label for="groupName">Group name</label>
				<input type="text" name="name" id="groupName" class="form-control"  value="<?=formFieldValue('name', $record);?>" />
			</div>

            <fieldset class="form-group">
                <div class="field">
                    <legend><?=__('Permissions');?></legend>

                    <select name="permissions[]" multiple>
						<?php foreach ($permissions as $id => $permission): ?>
                            <option value="<?= $id; ?>" <?= in_array($id, $record['permissions']) ? 'selected' : '' ?>><?= $permission; ?></option>
						<?php endforeach; ?>
                    </select>
                </div>
            </fieldset>
			<div class="field">
				<input type="submit" class="btn btn-primary" value="Save"/>
			</div>
		</form>
	</div>

<?php include __DIR__ . '../../layouts/after_app.phtml'; ?>