<?php include __DIR__ . '../../layouts/before_app.phtml'; ?>

	<div class="card">
		<h1><?= __(($record && $record['id']) ? 'Edit group (id: ' . $record['id'] . ')': 'Add group'); ?></h1>
		<form action="" method="POST">
			<input type="hidden" name="__csrf" value="<?=$csrf;?>"/>

			<div class="form-group">
				<label for="groupName">Group name</label>
				<input type="text" name="name" id="groupName" class="form-control"  value="<?=formFieldValue('name', $record);?>" />
			</div>
			<fieldset class="form-group">
				<legend><?=__('Permissions');?></legend>
				<?php $selectedPermissions = array_filter(formFieldValue('permissions', $record) ?: []); ?>
				<?php for($i = 0; $i <= count($selectedPermissions); $i++) { ?>
					<div class="field">
						<select name="group_permissions[]">
							<?=selectOptions($permissions, $selectedPermissions[$i] ?? null, ' - '.__('No permission').' - ');?>
						</select>
					</div>
				<?php } ?>
			</fieldset>
			<div class="field">
				<input type="submit" class="btn btn-primary" value="Save"/>
			</div>
		</form>
	</div>

<?php include __DIR__ . '../../layouts/after_app.phtml'; ?>