<?php include __DIR__ . '../../layouts/before_app.phtml'; ?>

<div class="card">

	<div class="d-flex w-100">
		<div class="mr-auto form-group">
			<a href="/admin/groups/add" class="btn btn-primary" >Add group</a>
		</div>
		<?php include __DIR__ . '/../parts/list_search.phtml'; ?>
	</div>

	<table class="table table-striped table-bordered">
		<thead>
		<tr>
			<th><?=sortableColumn('Name', 'name');?></th>
			<th>Actions</th>
		</tr>
		</thead>
		<tbody>
            <?php
				if (count($records) > 0):
					foreach ($records as $group):
			?>
					<tr>
						<td><?=$group['name'] ?? null;?></td>
						<td style="width:120px" class="actions">
							<a href="/admin/groups/show?id=<?=$group['id'];?>"><i class="fas fa-eye text-muted"></i></a>
							<a href="/admin/groups/edit?id=<?=$group['id'];?>"><i class="fas fa-edit"></i></a>
							<a href="/admin/groups/delete?id=<?=$group['id'];?>" onclick="return confirm('Are you sure to delete?')"><i class="fas fa-trash text-danger"></i></a>
						</td>
					</tr>
			<?php
					endforeach;
				else:
			?>
					<tr>
						<td colspan="2">
							There is no record to show.
						</td>
					</tr>
			<?
				endif;
            ?>
		</tbody>
		<tfoot>
		<tr>
			<td colspan="6">
				<div class="paginator">
					<?php include __DIR__.'/../parts/paginator.phtml';?>
				</div>
			</td>
		</tr>
		</tfoot>
	</table>
</div>
<?php include __DIR__ . '../../layouts/after_app.phtml'; ?>
