		</div>
		<footer>
			<a class="environ" href="https://environ.hu">environ.hu</a>
			<span class="logo-title">DAREFFORT - Environet</span>
			<div class="logos">
				<div class="logo"><img src="/img/dareffort_logo.png" alt="DAREFFORT"></div>
				<div class="logo"><img src="/img/eu_logo.jpg" alt="European Union"></div>
			</div>
		</footer>
	</section>
	<!--main content end-->
</section>
<!--container end-->
<?php include __DIR__ . '/after_content.phtml'; ?>