<?php include __DIR__.'/before_content.phtml';?>
<header id="siteHeader">
    <a href="#" id="sidebarToggle"><i class="fas fa-bars"></i></a>
    <div id="identity" class="dropdown">
        <!--<div class="summary">
            <div><?php echo $identity['name'] ?></div>
            <a href="#" class="dropdown-toggle"></a>
        </div>-->

        <!--<div class="dropdown-menu dropdown-menu-right">-->
            <a class="logout-link" href="#">
                <i class="fas fa-sign-out-alt"></i>
            </a>
            <form id="logout-form" action="/admin/logout" method="POST" style="display: none;">
                <input type="hidden" name="__csrf" value="<?=$csrf;?>"/>
            </form>
        <!-- </div> -->
    </div>
</header>
<section id="container">
    <!--sidebar start-->
    <aside id="sidebar">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu">
            <li class="">
                <?= includeTemplatePart('menuitem.phtml', ['title' => 'Dashboard', 'route' => '/admin', 'icon' => 'home', 'matchExtra' => 0]) ?>
            </li>

            <?php if($request->getIdentity()->hasPermissions(['admin.users.read'])): ?>
                <li>
                    <?= includeTemplatePart('menuitem.phtml', ['title' => 'Users', 'route' => '/admin/users', 'icon' => 'user', 'matchExtra' => 1]) ?>
                </li>
			<?php endif; ?>

            <?php if($request->getIdentity()->hasPermissions(['admin.groups.read'])): ?>
                <li>
                    <?= includeTemplatePart('menuitem.phtml', ['title' => 'Groups', 'route' => '/admin/groups', 'icon' => 'user-friends', 'matchExtra' => 1]) ?>
                </li>
            <?php endif; ?>

            <?php if($request->getIdentity()->hasPermissions(['admin.providers.read']) || $request->getIdentity()->hasPermissions(['admin.providers.readown'])): ?>
                <li>
                    <?= includeTemplatePart('menuitem.phtml', ['title' => 'Data providers', 'route' => '/admin/data-providers', 'icon' => 'address-book', 'matchExtra' => 1]) ?>
                </li>
			<?php endif; ?>

            <?php if($request->getIdentity()->hasPermissionsAnyOf([
                    'admin.hydro.monitoringpoints.read',
                    'admin.hydro.observedproperties.read',
                    'admin.hydro.waterbodies.read',
                    'admin.hydro.classifications.read',
                    'admin.hydro.results.read',
                    'admin.hydro.monitoringpoints.readown'
            ])): ?>
                <li class="sub-menu" data-id="hydroSubmenu" >
                    <?= includeTemplatePart('menuitem.phtml', ['title' => 'Hydro', 'route' => null, 'icon' => 'tint', 'matchExtra' => 0]) ?>
                    <ul class="sub">
	                    <?php if($request->getIdentity()->hasPermissions(['admin.hydro.monitoringpoints.read']) || $request->getIdentity()->hasPermissions(['admin.hydro.monitoringpoints.readown'])): ?>
                            <li>
                                <?= includeTemplatePart('menuitem.phtml', ['title' => 'Monitoring points', 'route' => '/admin/hydro/monitoring-points', 'icon' => 'tachometer-alt', 'matchExtra' => 1]) ?>
                            </li>
						<?php endif; ?>
	                    <?php if($request->getIdentity()->hasPermissions(['admin.hydro.observedproperties.read'])): ?>
                            <li>
                                <?= includeTemplatePart('menuitem.phtml', ['title' => 'Observed properties', 'route' => '/admin/hydro/observed-properties', 'icon' => 'eye', 'matchExtra' => 1]) ?>
                            </li>
						<?php endif; ?>
	                    <?php if($request->getIdentity()->hasPermissions(['admin.hydro.waterbodies.read'])): ?>
                            <li>
                                <?= includeTemplatePart('menuitem.phtml', ['title' => 'Waterbodies', 'route' => '/admin/hydro/waterbodies', 'icon' => 'water', 'matchExtra' => 1]) ?>
                            </li>
						<?php endif; ?>
	                    <?php if($request->getIdentity()->hasPermissions(['admin.hydro.classifications.read'])): ?>
                            <li>
                                <?= includeTemplatePart('menuitem.phtml', ['title' => 'Station classifications', 'route' => '/admin/hydro/station-classifications', 'icon' => 'certificate', 'matchExtra' => 1]) ?>
                            </li>
						<?php endif; ?>
						<?php if($request->getIdentity()->hasPermissions(['admin.hydro.riverbanks.read'])): ?>
                            <li>
								<?= includeTemplatePart('menuitem.phtml', ['title' => 'Riverbanks', 'route' => '/admin/hydro/riverbanks', 'icon' => 'certificate', 'matchExtra' => 1]) ?>
                            </li>
						<?php endif; ?>
	                    <?php if($request->getIdentity()->hasPermissions(['admin.hydro.results.read'])): ?>
                            <li>
                                <?= includeTemplatePart('menuitem.phtml', ['title' => 'Results', 'route' => '/admin/hydro/results', 'icon' => 'chart-pie', 'matchExtra' => 1]) ?>
                            </li>
						<?php endif; ?>
                    </ul>
                </li>
			<?php endif; ?>

            <?php if($request->getIdentity()->hasPermissionsAnyOf([
                    'admin.meteo.monitoringpoints.read',
                    'admin.meteo.observedproperties.read',
                    'admin.meteo.classifications.read',
                    'admin.meteo.results.read',
				    'admin.meteo.monitoringpoints.readown'
            ])): ?>
                <li class="sub-menu" data-id="meteoSubmenu" >
                    <?= includeTemplatePart('menuitem.phtml', ['title' => 'Meteo', 'route' => null, 'icon' => 'cloud', 'matchExtra' => 1]) ?>
                    <ul class="sub">
	                    <?php if($request->getIdentity()->hasPermissions(['admin.meteo.monitoringpoints.read']) || $request->getIdentity()->hasPermissions(['admin.meteo.monitoringpoints.readown'])): ?>
                            <li>
                                <?= includeTemplatePart('menuitem.phtml', ['title' => 'Monitoring points', 'route' => '/admin/meteo/monitoring-points', 'icon' => 'tachometer-alt', 'matchExtra' => 1]) ?>
                            </li>
						<?php endif; ?>
	                    <?php if($request->getIdentity()->hasPermissions(['admin.meteo.observedproperties.read'])): ?>
                            <li>
                                <?= includeTemplatePart('menuitem.phtml', ['title' => 'Observed properties', 'route' => '/admin/meteo/observed-properties', 'icon' => 'eye', 'matchExtra' => 1]) ?>
                            </li>
						<?php endif; ?>
	                    <?php if($request->getIdentity()->hasPermissions(['admin.meteo.classifications.read'])): ?>
                            <li>
                                <?= includeTemplatePart('menuitem.phtml', ['title' => 'Station classifications', 'route' => '/admin/meteo/station-classifications', 'icon' => 'certificate', 'matchExtra' => 1]) ?>
                            </li>
						<?php endif; ?>
	                    <?php if($request->getIdentity()->hasPermissions(['admin.meteo.results.read'])): ?>
                            <li>
                                <?= includeTemplatePart('menuitem.phtml', ['title' => 'Results', 'route' => '/admin/meteo/results', 'icon' => 'chart-pie', 'matchExtra' => 1]) ?>
                            </li>
						<?php endif; ?>
                    </ul>
                </li>
			<?php endif; ?>
            <?php if($request->getIdentity()->hasPermissions(['admin.measurementaccessrules.read']) || $request->getIdentity()->hasPermissions(['admin.measurementaccessrules.readown'])): ?>
                <li>
                    <?= includeTemplatePart('menuitem.phtml', ['title' => 'Measurement access rules', 'route' => '/admin/measurement-access-rules', 'icon' => 'database', 'matchExtra' => 1]) ?>
                </li>
			<?php endif; ?>
            <?php if($request->getIdentity()->hasPermissions(['admin.missingData.upload']) || $request->getIdentity()->hasPermissions(['admin.missingData.uploadown'])): ?>
                <li>
                    <?=includeTemplatePart('menuitem.phtml', ['title' => 'Upload missing data', 'route' => '/admin/missing-data', 'icon' => 'upload', 'matchExtra' => 1]) ?>
                </li>
			<?php endif; ?>
            <?php if($request->getIdentity()->hasPermissions(['admin.processedData.upload']) || $request->getIdentity()->hasPermissions(['admin.processedData.uploadown'])): ?>
                <li>
                    <?=includeTemplatePart('menuitem.phtml', ['title' => 'Upload processed data', 'route' => '/admin/processed-data', 'icon' => 'upload', 'matchExtra' => 1]) ?>
                </li>
			<?php endif; ?>
        </ul>
        <!-- sidebar menu end-->
    </aside>
    <!--sidebar end-->

    <!--main content start-->
    <section id="main-content">
        <div class="main-content-wrapper">
        <?php include __DIR__.'/../parts/messages.phtml'; //Render flash messages?>