<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card">
    <h1>Meteo station classifications</h1>
	<div class="d-flex w-100">
		<div class="mr-auto form-group">
			<a href="/admin/meteo/station-classifications/add" class="btn btn-primary" >Add station classification</a>
		</div>
		<div class="form-group">
			<form method="get">
				<input type="search" name="search" class="form-control" placeholder="<?=__('Search')?>" value="<?=htmlspecialchars(urldecode($searchString))?>">
			</form>
		</div>
	</div>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th><?=sortableColumn('Value', 'value');?></th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php
				if (count($records) > 0):
					foreach ($records as $record):
			?>
                <tr>
                    <td><?=$record['value'] ?? null;?></td>
                    <td class="actions">
                        <a href="/admin/meteo/station-classifications/show?id=<?=$record['id'];?>"><i class="fas fa-eye text-muted"></i></a>
                        <a href="/admin/meteo/station-classifications/edit?id=<?=$record['id'];?>"><i class="fas fa-edit"></i></a>
                        <a href="/admin/hydro/station-classifications/delete?id=<?=$record['id'];?>" onclick="return confirm('Are you sure you want to delete this station classification?')"><i class="fas fa-trash text-danger"></i></a>
                    </td>
                </tr>
			<?php
					endforeach;
				else:
			?>
					<tr>
						<td colspan="2">
							There is no record to show.
						</td>
					</tr>
			<?
				endif;
            ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">
                    <div class="paginator">
                        <?php include __DIR__.'/../../parts/paginator.phtml';?>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
