<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card">
	<?=includeTemplatePart('crud_list_header.phtml', get_defined_vars() + [
		'addUrl' => '/admin/hydro/river-basins/add',
		'addTitle' => 'Add river basin'
	]);?>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th><?=sortableColumn('Id', 'id');?></th>
                <th><?=sortableColumn('Name', 'name');?></th>
                <th class="actions">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php
				if (count($records) > 0):
					foreach ($records as $record):
			?>
                <tr>
                    <td><?=$record['id'] ?? null;?></td>
                    <td><?=$record['name'] ?? null;?></td>
                    <td class="actions">
                        <a href="/admin/hydro/river-basins/show?id=<?=$record['id'];?>"><i class="fas fa-eye text-muted"></i></a>
                        <a href="/admin/hydro/river-basins/edit?id=<?=$record['id'];?>"><i class="fas fa-edit"></i></a>
                    </td>
                </tr>
			<?php
					endforeach;
				else:
			?>
					<tr>
						<td colspan="3">
							There is no record to show.
						</td>
					</tr>
			<?
				endif;
            ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">
                    <div class="paginator">
                        <?php include __DIR__.'/../../parts/paginator.phtml';?>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
