<?php include __DIR__ . '../../layouts/before_app.phtml'; ?>

	<div class="card formPage">
		<?=includeTemplatePart('crud_show_header.phtml', get_defined_vars());?>
		<form action="" method="POST">
			<input type="hidden" name="__csrf" value="<?=$csrf;?>"/>

			<div class="form-group">
				<label for="groupName">Warning level group name</label>
				<input type="text" name="name" id="groupName" class="form-control <?=isFieldInvalidClass('name', get_defined_vars());?>"  value="<?=formFieldValue('name', $record);?>" />
				<div class="invalid-feedback">
					<?=getFieldInvalidMessage('name', get_defined_vars());?>
				</div>
			</div>
			<div class="field">
				<input type="submit" class="btn btn-primary" value="Save"/>
			</div>
		</form>
	</div>

<?php include __DIR__ . '../../layouts/after_app.phtml'; ?>