<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card formPage">
	<?=includeTemplatePart('crud_show_header.phtml', get_defined_vars());?>
	<form action="" novalidate class="needs-validation" method="POST">
        <input type="hidden" name="__csrf" value="<?=$csrf;?>"/>
        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" name="name" id="name" class="form-control <?=isFieldInvalidClass('name', get_defined_vars());?>" required value="<?=formFieldValue('name', $record);?>" />
      			<div class="invalid-feedback">
      		        <?=getFieldInvalidMessage('name', get_defined_vars(), 'Please provide a valid name!');?>
      			</div>
        </div>

        <div class="mb-3">
            <label for="country" class="form-label">Country code (ISO3166-1 ALPHA-2)</label>
            <input type="text" name="country" id="country" maxlength="2" class="form-control <?=isFieldInvalidClass('country', get_defined_vars());?>" value="<?=formFieldValue('country', $record);?>" />
      			<div class="invalid-feedback">
      		        <?=getFieldInvalidMessage('country', get_defined_vars());?>
      			</div>
    		</div>

        <div class="mb-3">
            <label for="ncd_pst" class="form-label">National code of the meteorological station</label>
            <input type="text" name="ncd_pst" id="ncd_pst" class="form-control <?=isFieldInvalidClass('ncd_pst', get_defined_vars());?>" required value="<?=formFieldValue('ncd_pst', $record);?>" />
      			<div class="invalid-feedback">
      		        <?=getFieldInvalidMessage('ncd_pst', get_defined_vars(), 'Please provide a valid national code value!');?>
      			</div>
        </div>

		<?php if($request->getIdentity()->hasPermissions(['admin.all']) || $request->getIdentity()->hasPermissions(['admin.meteo.monitoringpoints.update'])): ?>
			<div class="mb-3">
				<label for="eucd_pst" class="form-label">International code of the meteorological station
					<?php if($record) : ?>
						<small>(Current value: <?=$record['eucd_pst'] ?? null;?>)</small>
					<?php endif; ?>
				</label>
				<input type="text" name="eucd_pst" id="eucd_pst" class="form-control <?=isFieldInvalidClass('eucd_pst', get_defined_vars());?>" value="<?=formFieldValue('eucd_pst');?>" autocomplete="off" />
				<small class="form-text text-muted">Fill it only if you want to set a custom value instead of auto-generated.</small>
			</div>
		<?php endif; ?>

		<div class="form-check mb-3">
			<input type="hidden" name="is_active" value="0"/>
			<input type="checkbox" name="is_active" id="is_active" value="1" class="form-check-input" <?=formFieldValue('is_active', $record) ? 'checked' : '';?>/>
			<label for="is_active" class="form-check-label">Is active</label>
		</div>

        <div class="form-check mb-3">
            <input type="hidden" name="is_out_of_order" value="0"/>
            <input type="checkbox" name="is_out_of_order" id="is_out_of_order" value="1" class="form-check-input" <?=formFieldValue('is_out_of_order', $record) ? 'checked' : '';?>/>
            <label for="is_out_of_order" class="form-check-label">Is ouf of order</label>
        </div>

        <div class="mb-3">
            <label for="lat" class="form-label">Latitude coordinate</label>
            <input type="number" name="lat" id="lat" step="0.000001" class="form-control" value="<?=formFieldValue('lat', $record);?>" />
        </div>

        <div class="mb-3">
            <label for="long" class="form-label">Longitude coordinate</label>
            <input type="number" name="long" id="long" step="0.000001" class="form-control" value="<?=formFieldValue('long', $record);?>" />
        </div>

        <div class="mb-3">
            <label for="z" class="form-label">Z coordinate</label>
            <input type="number" name="z" id="z" step="0.000001" class="form-control" value="<?=formFieldValue('z', $record);?>" />
        </div>

        <div class="mb-3">
            <label for="altitude" class="form-label">Altitude</label>
            <input type="number" name="altitude" id="altitude" step="0.000001" class="form-control" value="<?=formFieldValue('altitude', $record);?>" />
        </div>

        <div class="mb-3">
            <label for="vertical_reference" class="form-label">Vertical reference</label>
            <input type="text" name="vertical_reference" id="vertical_reference" class="form-control" value="<?=formFieldValue('vertical_reference', $record);?>" />
        </div>

        <div class="mb-3">
            <label for="location" class="form-label">Location</label>
            <input type="text" name="location" id="location" class="form-control" value="<?=formFieldValue('location', $record);?>" />
        </div>

		<fieldset class="mb-3">
			<legend><?=__('Sub-basin');?></legend>
			<?php $selectedRiverBasin = formFieldValue('river_basin_id', $record); ?>
			<div class="field">
				<select name="river_basin_id" class="form-select">
					<?=selectOptions($riverBasins, $selectedRiverBasin ?? null, ' - '.__('No sub-basin').' - ');?>
				</select>
			</div>
		</fieldset>

        <div class="mb-3">
            <label for="start_time" class="form-label">Start time</label>
            <input type="date" name="start_time" id="start_time" class="form-control" value="<?=isset($record['start_time']) ? date('Y-m-d', strtotime($record['start_time'])) : ''?>" />
        </div>

        <div class="mb-3">
            <label for="end_time" class="form-label">End time</label>
            <input type="date" name="end_time" id="end_time" class="form-control" value="<?=isset($record['end_time']) ? date('Y-m-d', strtotime($record['end_time'])) : ''?>" />
        </div>

        <fieldset class="mb-3">
            <legend><?=__('Station classification');?></legend>
            <?php $selectedClassification = formFieldValue('classification', $record); ?>
            <div class="field">
                <select name="classification" class="form-select">
                    <?=selectOptions($classifications, $selectedClassification ?? null, ' - '.__('No classification').' - ');?>
                </select>
            </div>
        </fieldset>

        <fieldset class="mb-3">
            <legend><?=__('Operator');?></legend>
			<?php $selectedOperator = formFieldValue('operator', $record); ?>
            <div class="field">
                <select name="operator" class="form-select <?=isFieldInvalidClass('operator', get_defined_vars());?>">
					<?=selectOptions($operators, $selectedOperator ?? null, ' - '.__('No operator').' - ');?>
                </select>
				<div class="invalid-feedback">
		            <?=getFieldInvalidMessage('operator', get_defined_vars());?>
				</div>
            </div>
        </fieldset>

        <fieldset class="mb-3">
            <div class="field">
                <legend><?=__('Observed properties');?></legend>
                <select name="observedProperties[]" class="form-select" multiple>
					<?php foreach ($observedProperties as $id => $symbol): ?>
                        <option value="<?= $id; ?>" <?= in_array($id, $record['observedProperties']) ? 'selected' : '' ?>><?= $symbol; ?></option>
					<?php endforeach; ?>
                </select>
            </div>
        </fieldset>

        <div class="field">
            <input type="submit" class="btn btn-primary" value="Save"/>
        </div>
    </form>
</div>

<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
