<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card">
    <h1>Meteo monitoring point<?= $record && $record['id'] ? '(id: ' . $record['id'] . ')': ''?></h1>
    <form action="" method="POST">
        <input type="hidden" name="__csrf" value="<?=$csrf;?>"/>
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" class="form-control" value="<?=formFieldValue('name', $record);?>" />
        </div>

        <div class="form-group">
            <label for="eucd_pst">Eucd pst</label>
            <input type="text" name="eucd_pst" id="eucd_pst" class="form-control" value="<?=formFieldValue('eucd_pst', $record);?>" />
        </div>

        <div class="form-group">
            <label for="ncd_pst">Ncd pst</label>
            <input type="text" name="ncd_pst" id="ncd_pst" class="form-control" value="<?=formFieldValue('ncd_pst', $record);?>" />
        </div>

        <div class="form-group">
            <label for="vertical_reference">Vertical reference</label>
            <input type="text" name="vertical_reference" id="vertical_reference" class="form-control" value="<?=formFieldValue('vertical_reference', $record);?>" />
        </div>

        <div class="form-group">
            <label for="country">Country</label>
            <input type="text" name="country" id="country" class="form-control" value="<?=formFieldValue('country', $record);?>" />
        </div>

        <div class="form-group">
            <label for="lat">Lat</label>
            <input type="text" name="lat" id="lat" class="form-control" value="<?=formFieldValue('lat', $record);?>" />
        </div>

        <div class="form-group">
            <label for="long">Long</label>
            <input type="text" name="long" id="long" class="form-control" value="<?=formFieldValue('long', $record);?>" />
        </div>

        <div class="form-group">
            <label for="z">Z</label>
            <input type="text" name="z" id="z" class="form-control" value="<?=formFieldValue('z', $record);?>" />
        </div>

        <div class="form-group">
            <label for="altitude">Altitude</label>
            <input type="text" name="altitude" id="altitude" class="form-control" value="<?=formFieldValue('altitude', $record);?>" />
        </div>

        <div class="form-group">
            <label for="location">Location</label>
            <input type="text" name="location" id="location" class="form-control" value="<?=formFieldValue('location', $record);?>" />
        </div>

        <div class="form-group">
            <label for="river_basin">River basin</label>
            <input type="text" name="river_basin" id="river_basin" class="form-control" value="<?=formFieldValue('river_basin', $record);?>" />
        </div>

        <fieldset class="form-group">
            <legend><?=__('Classification');?></legend>
            <?php $selectedClassification = formFieldValue('classification', $record); ?>
            <div class="field">
                <select name="classification">
                    <?=selectOptions($classifications, $selectedClassification ?? null, ' - '.__('No classification').' - ');?>
                </select>
            </div>
        </fieldset>

        <fieldset class="form-group">
            <legend><?=__('Operator');?></legend>
			<?php $selectedOperator = formFieldValue('operator', $record); ?>
            <div class="field">
                <select name="operator">
					<?=selectOptions($operators, $selectedOperator ?? null, ' - '.__('No operator').' - ');?>
                </select>
            </div>
        </fieldset>

		<fieldset class="form-group">
			<legend><?=__('Observed property(/ies)');?></legend>
		    <?php $selectedProperties = array_filter(formFieldValue('observedProperties', $record) ?: []); ?>
		    <?php for($i = 0; $i <= count($selectedProperties); $i++) { ?>
				<div class="field">
					<select name="observedProperties[<?=isset($selectedProperties[$i]) ? $selectedProperties[$i] : ''?>]">
					    <?=selectOptions($observedProperties, $selectedProperties[$i] ?? null, ' - '.__('No property').' - ');?>
					</select>
				</div>
		    <?php } ?>
		</fieldset>

        <div class="field">
            <input type="submit" class="btn btn-primary" value="Save"/>
        </div>
    </form>
</div>

<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
