<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card">
	<?=includeTemplatePart('crud_list_header.phtml', get_defined_vars() + [
			'addUrl' => '/admin/meteo/monitoring-points/add',
			'addTitle' => 'Add meteo monitoring point'
		]);?>
	<div class="mb-2">
		<a href="/admin/meteo/monitoring-points/csv-upload" class="btn btn-secondary">Upload CSV</a>
	</div>

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th><?=sortableColumn('Name', 'name');?></th>
        				<th class="fit-content"><?=sortableColumn('Active', 'is_active');?></th>
                <th class="fit-content"><?=sortableColumn('Out of order', 'is_out_of_order');?></th>
				        <th class="fit-content"><?=sortableColumn('Country', 'country');?></th>
				        <th class="fit-content"><?=sortableColumn('National code', 'ncd_pst');?></th>
                <th><?=sortableColumn('Operator', 'operator');?></th>
                <th class="actions">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php
				if (count($records) > 0):
					foreach ($records as $record):
			?>
                <tr>
                    <td><?=$record['name'] ?? null;?></td>
					          <td class="fit-content"><i class="fa <?=$record['is_active'] ? 'fa-check text-success' : 'fa-times text-danger';?>"></i></td>
                    <td class="fit-content"><i class="fa <?=$record['is_out_of_order'] ? 'fa-ban text-danger' : '';?>"></i></td>
					          <td class="fit-content"><?=$record['country'] ?? null;?></td>
					          <td><?=$record['ncd_pst'] ?? null;?></td>
                    <td class="text-truncate" title="<?=$record['operator'] ?? null;?>"><?=$record['operator'] ?? null;?></td>
                    <td class="actions">
                        <a href="/admin/meteo/monitoring-points/show?id=<?=$record['id'];?>"><i class="fas fa-eye text-muted"></i></a>
                        <a href="/admin/meteo/monitoring-points/edit?id=<?=$record['id'];?>"><i class="fas fa-edit"></i></a>
	                    <?=$identity['is_super_admin'] ? '<a href="/admin/meteo/monitoring-points/delete?id='.$record['id'].'" onclick="return confirm(\'Are you absolutely sure you want to delete this monitoring point and all data that belongs to it (time series, results, linked observed properties)?\')"><i class="fas fa-trash text-danger"></i></a>' : '';?>
                    </td>
                </tr>
			<?php
					endforeach;
				else:
			?>
					<tr>
						<td colspan="6">
							There is no record to show.
						</td>
					</tr>
			<?
				endif;
            ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="6">
                    <div class="paginator">
                        <?php include __DIR__.'/../../parts/paginator.phtml';?>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
