<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card">
	<?=includeTemplatePart('crud_list_header.phtml', get_defined_vars() + [
			'addUrl' => '/admin/meteo/monitoring-points/add',
			'addTitle' => 'Add meteo monitoring point'
		]);?>
	<?=includeTemplatePart('csvuploadbutton.phtml', [
		'uploadEndpoint' => '/admin/meteo/monitoring-points/csv-upload'
	]); ?>

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th><?=sortableColumn('Name', 'name');?></th>
                <th class="fit-content"><?=sortableColumn('Country', 'country');?></th>
                <th><?=sortableColumn('Operator', 'operator');?></th>
                <th class="actions">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php
				if (count($records) > 0):
					foreach ($records as $record):
			?>
                <tr>
                    <td><?=$record['name'] ?? null;?></td>
                    <td class="fit-content"><?=$record['country'] ?? null;?></td>
                    <td class="text-truncate" title="<?=$record['operator'] ?? null;?>"><?=$record['operator'] ?? null;?></td>
                    <td class="actions">
                        <a href="/admin/meteo/monitoring-points/show?id=<?=$record['id'];?>"><i class="fas fa-eye text-muted"></i></a>
                        <a href="/admin/meteo/monitoring-points/edit?id=<?=$record['id'];?>"><i class="fas fa-edit"></i></a>
                        <a href="/admin/meteo/monitoring-points/delete?id=<?=$record['id'];?>" onclick="return confirm('Are you sure you want to delete this monitoring point?')"><i class="fas fa-trash text-danger"></i></a>
                    </td>
                </tr>
			<?php
					endforeach;
				else:
			?>
					<tr>
						<td colspan="4">
							There is no record to show.
						</td>
					</tr>
			<?
				endif;
            ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">
                    <div class="paginator">
                        <?php include __DIR__.'/../../parts/paginator.phtml';?>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
