<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card showPage">
	<?=includeTemplatePart('crud_show_header.phtml', get_defined_vars() + [
		'editUrl' => '/admin/meteo/monitoring-points/edit?id='.$record['id'],
	]);?>

    <dl class="row">
        <dt class="col-sm-3">ID</dt>
        <dd class="col-sm-9">#<?=$record['id'] ?? '';?></dd>

        <dt class="col-sm-3">Name</dt>
        <dd class="col-sm-9"><?=$record['name'] ?? '';?></dd>

    		<dt class="col-sm-3">Country code</dt>
    		<dd class="col-sm-9"><?=$record['country'] ?? '';?></dd>

        <dt class="col-sm-3">National code of the meteorological station</dt>
        <dd class="col-sm-9"><?=$record['ncd_pst'] ?? '';?></dd>

        <dt class="col-sm-3">International code of the meteorological station</dt>
        <dd class="col-sm-9"><?=$record['eucd_pst'] ?? '';?></dd>

        <dt class="col-sm-3">Is active</dt>
        <dd class="col-sm-9"><?=$record['is_active'] ? 'Yes' : 'No';?></dd>

        <dt class="col-sm-3">Is out of order</dt>
        <dd class="col-sm-9"><?=$record['is_out_of_order'] ? 'Yes' : 'No';?></dd>

        <dt class="col-sm-3">Latitude coordinate</dt>
        <dd class="col-sm-9"><?=$record['lat'] ?? '';?></dd>

        <dt class="col-sm-3">Longitude coordinate</dt>
        <dd class="col-sm-9"><?=$record['long'] ?? '';?></dd>

        <dt class="col-sm-3">Z coordinate</dt>
        <dd class="col-sm-9"><?=$record['z'] ?? '';?></dd>

<!-- Not editable, not used:
        <dt class="col-sm-3">Map Latitude coordinate</dt>
        <dd class="col-sm-9"><?=$record['maplat'] ?? '';?></dd>

        <dt class="col-sm-3">Map Longitude coordinate</dt>
        <dd class="col-sm-9"><?=$record['maplong'] ?? '';?></dd>

        <dt class="col-sm-3">UTC Offset</dt>
        <dd class="col-sm-9"><?=$record['utc_offset'] ?? '';?></dd>

-->
        <dt class="col-sm-3">Altitude</dt>
        <dd class="col-sm-9"><?=$record['altitude'] ?? '';?></dd>

        <dt class="col-sm-3">Vertical reference</dt>
        <dd class="col-sm-9"><?=$record['vertical_reference'] ?? '';?></dd>

    		<dt class="col-sm-3">Location</dt>
    		<dd class="col-sm-9"><?=$record['location'] ?? '';?></dd>

		<dt class="col-sm-3">River basin</dt>
		<dd class="col-sm-9">
		    <?php if(!empty($record['river_basin_id'])): ?>
				<a href="/admin/hydro/river-basins/show?id=<?= $record['river_basin']['id'] ;?>">#<?= $record['river_basin']['name'] ?></a>
		    <?php endif; ?>
		</dd>

        <dt class="col-sm-3">Start time</dt>
        <dd class="col-sm-9"><?=$record['start_time'] ?? '';?></dd>

        <dt class="col-sm-3">End time</dt>
        <dd class="col-sm-9"><?=$record['end_time'] ?? '';?></dd>

		<dt class="col-sm-3">Last updated at</dt>
		<dd class="col-sm-9"><?=$record['last_updated_at'] ?? '';?></dd>

		<dt class="col-sm-3">Last updated by</dt>
		<dd class="col-sm-9">
		    <?php if(!empty($record['last_updated_by_user'])): ?>
				<a href="/admin/users/show?id=<?= $record['last_updated_by'] ;?>">#<?= $record['last_updated_by'] ?></a>
				<span><?=$record['last_updated_by_user']['username'] ?? null;?></span>
		    <?php endif; ?>
		</dd>

        <dt class="col-sm-3">Station classification</dt>
        <dd class="col-sm-9">
			<?php if(!empty($record['classification'])): ?>
                <a href="/admin/meteo/station-classifications?id=<?= $record['classification']['id'] ;?>">#<?= $record['classification']['id'] ?></a>
                <span><?=$record['classification']['value'] ?? null;?></span>
            <?php endif; ?>
        </dd>

    		<dt class="col-sm-3">Operator</dt>
    		<dd class="col-sm-9">
    		    <?php if(!empty($record['operator'])): ?>
    				<a href="/admin/operators/show?id=<?= $record['operator']['id'] ;?>">#<?= $record['operator']['id'] ?></a>
    				<span><?=$record['operator']['name'] ?? null;?></span>
    		    <?php endif; ?>
    		</dd>

    		<dt class="col-sm-3">Observerd properties</dt>
    		<dd class="col-sm-9">
    			<?php foreach ($record['showObservedProperty'] ?: [] as $property) { ?>
    				<a href="/admin/meteo/observed-properties/edit?id=<?=$property['id'];?>">#<?=$property['symbol'] ?? null;?></a><br>
    			<?php } ?>
    		</dd>
    </dl>
</div>
<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
