<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card showPage">
	<div class="actions">
		<a href="/admin/hydro/monitoring-points/edit?id=<?=$record['id'];?>" class="btn btn-primary">Edit monitoring point</a>
		<a href="<?=$listPage;?>" class="btn btn-secondary">Back to list</a>
	</div>

    <h1>Meteo monitoring point #<?=$record['id'] ?? '';?></h1>

    <dl class="row">
        <dt class="col-sm-3">ID</dt>
        <dd class="col-sm-9">#<?=$record['id'] ?? '';?></dd>

        <dt class="col-sm-3">Name</dt>
        <dd class="col-sm-9"><?=$record['name'] ?? '';?></dd>

        <dt class="col-sm-3">EUCD PSD</dt>
        <dd class="col-sm-9"><?=$record['eucd_pst'] ?? '';?></dd>

        <dt class="col-sm-3">NCD PST</dt>
        <dd class="col-sm-9"><?=$record['ncd_pst'] ?? '';?></dd>

		<dt class="col-sm-3">Operator</dt>
		<dd class="col-sm-9">
		    <?php if(!empty($record['operator'])): ?>
				<a href="/admin/data-providers?id=<?= $record['operator']['id'] ;?>">#<?= $record['operator']['id'] ?></a>
				<span><?=$record['operator']['name'] ?? null;?></span>
		    <?php endif; ?>
		</dd>

		<dt class="col-sm-3">Country</dt>
		<dd class="col-sm-9"><?=$record['country'] ?? '';?></dd>

		<dt class="col-sm-3">Location</dt>
		<dd class="col-sm-9"><?=$record['location'] ?? '';?></dd>

		<dt class="col-sm-3">River basin</dt>
		<dd class="col-sm-9"><?=$record['river_basin'] ?? '';?></dd>

        <dt class="col-sm-3">Latitude coordinate</dt>
        <dd class="col-sm-9"><?=$record['lat'] ?? '';?></dd>

        <dt class="col-sm-3">Longitude coordinate</dt>
        <dd class="col-sm-9"><?=$record['long'] ?? '';?></dd>

        <dt class="col-sm-3">Z coordinate</dt>
        <dd class="col-sm-9"><?=$record['z'] ?? '';?></dd>

        <dt class="col-sm-3">Altitude</dt>
        <dd class="col-sm-9"><?=$record['altitude'] ?? '';?></dd>

        <dt class="col-sm-3">Map Latitude coordinate</dt>
        <dd class="col-sm-9"><?=$record['maplat'] ?? '';?></dd>

        <dt class="col-sm-3">Map Longitude coordinate</dt>
        <dd class="col-sm-9"><?=$record['maplong'] ?? '';?></dd>

        <dt class="col-sm-3">Start time</dt>
        <dd class="col-sm-9"><?=$record['start_time'] ?? '';?></dd>

        <dt class="col-sm-3">End time</dt>
        <dd class="col-sm-9"><?=$record['end_time'] ?? '';?></dd>

        <dt class="col-sm-3">UTC Offset</dt>
        <dd class="col-sm-9"><?=$record['utc_offset'] ?? '';?></dd>

        <dt class="col-sm-3">Vertical reference</dt>
        <dd class="col-sm-9"><?=$record['vertical_reference'] ?? '';?></dd>

        <dt class="col-sm-3">Station classification</dt>
        <dd class="col-sm-9">
			<?php if(!empty($record['classification'])): ?>
                <a href="/admin/meteo/station-classifications?id=<?= $record['classification']['id'] ;?>">#<?= $record['classification']['id'] ?></a>
                <span><?=$record['classification']['value'] ?? null;?></span>
            <?php endif; ?>
        </dd>

		<dt class="col-sm-3">Observerd properties</dt>
		<dd class="col-sm-9">
			<?php foreach ($record['showObservedProperty'] ?: [] as $property) { ?>
				<a href="/admin/meteo/observed-properties/edit?id=<?=$property['id'];?>">#<?=$property['symbol'] ?? null;?></a><br>
			<?php } ?>
		</dd>
    </dl>
</div>
<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
