<?php include __DIR__ . '/../../layouts/before_app.phtml'; ?>
<div class="card formPage">
	<?=includeTemplatePart('crud_show_header.phtml', get_defined_vars());?>
	<form action="" method="POST">
		<input type="hidden" name="__csrf" value="<?=$csrf;?>"/>

        <div class="mb-3">
            <label for="symbol" class="form-label">Symbol</label>
            <input type="text" name="symbol" id="symbol" class="form-control <?=isFieldInvalidClass('symbol', get_defined_vars());?>"  value="<?=formFieldValue('symbol', $record);?>" />
			<div class="invalid-feedback">
		        <?=getFieldInvalidMessage('symbol', get_defined_vars());?>
			</div>
        </div>

        <div class="mb-3">
            <label for="unit" class="form-label">Unit</label>
            <input type="text" name="unit" id="unit" class="form-control"  value="<?=formFieldValue('unit', $record);?>" />
        </div>

        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <input type="text" name="description" id="description" class="form-control"  value="<?=formFieldValue('description', $record);?>" />
        </div>

		<fieldset class="mb-3">
			<legend>Type</legend>
			<div class="field">
				<select name="type" class="form-select">
					<?=selectOptions(observedPropertyTypeOptions(), formFieldValue('type', $record));?>
				</select>
			</div>
		</fieldset>

        <div class="field">
            <input type="submit" class="btn btn-primary" value="Save"/>
        </div>
    </form>
</div>

<?php include __DIR__ . '/../../layouts/after_app.phtml'; ?>
