<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card">
    <h1>Hydro monitoring point<?= $record && $record['id'] ? '(id: ' . $record['id'] . ')': ''?></h1>
    <form action="" novalidate class="needs-validation" method="POST">
        <input type="hidden" name="__csrf" value="<?=$csrf;?>"/>
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" class="form-control" required value="<?=formFieldValue('name', $record);?>" />
            <div class="invalid-feedback">
                Please provide a valid name!
            </div>
        </div>

        <div class="form-group">
            <label for="eucd_wgst">Eucd wgst</label>
            <input type="text" name="eucd_wgst" id="eucd_wgst" class="form-control" required value="<?=formFieldValue('eucd_wgst', $record);?>" />
            <div class="invalid-feedback">
                Please provide a valid Eucd wgst value!
            </div>
        </div>

        <div class="form-group">
            <label for="ncd_wgst">Ncd wgst</label>
            <input type="text" name="ncd_wgst" id="ncd_wgst" class="form-control" required value="<?=formFieldValue('ncd_wgst', $record);?>" />
            <div class="invalid-feedback">
                Please provide a valid Ncd wgst value!
            </div>
        </div>

        <div class="form-group">
            <label for="vertical_reference">Vertical reference</label>
            <input type="text" name="vertical_reference" id="vertical_reference" class="form-control" value="<?=formFieldValue('vertical_reference', $record);?>" />
        </div>

        <div class="form-group">
            <label for="country">Country</label>
            <input type="text" name="country" id="country" maxlength="2" class="form-control" value="<?=formFieldValue('country', $record);?>" />
        </div>

        <div class="form-group">
            <label for="lat">Lat</label>
            <input type="number" name="lat" id="lat" step="0.000001" class="form-control" value="<?=formFieldValue('lat', $record);?>" />
        </div>

        <div class="form-group">
            <label for="long">Long</label>
            <input type="number" name="long" id="long" step="0.000001" class="form-control" value="<?=formFieldValue('long', $record);?>" />
        </div>

        <div class="form-group">
            <label for="z">Z</label>
            <input type="number" name="z" id="z" step="0.000001" class="form-control" value="<?=formFieldValue('z', $record);?>" />
        </div>

        <div class="form-group">
            <label for="location">Location</label>
            <input type="text" name="location" id="location" class="form-control" value="<?=formFieldValue('location', $record);?>" />
        </div>

        <div class="form-group">
            <label for="river_kilometer">River kilometer</label>
            <input type="number" name="river_kilometer" id="river_kilometer" step="0.000001"  class="form-control" value="<?=formFieldValue('river_kilometer', $record);?>" />
        </div>

        <div class="form-group">
            <label for="catchment_area">Catchment area</label>
            <input type="number" name="catchment_area" id="catchment_area" step="0.000001"  class="form-control" value="<?=formFieldValue('catchment_area', $record);?>" />
        </div>

        <div class="form-group">
            <label for="gauge_zero">Gauge zero</label>
            <input type="number" name="gauge_zero" id="gauge_zero" step="0.000001"  class="form-control" value="<?=formFieldValue('gauge_zero', $record);?>" />
        </div>

        <div class="form-group">
            <label for="river_basin">River basin</label>
            <input type="text" name="river_basin" id="river_basin" class="form-control" value="<?=formFieldValue('river_basin', $record);?>" />
        </div>

        <div class="form-group">
            <label for="start_time">Start time</label>
            <input type="date" name="start_time" id="start_time" class="form-control" value="<?=isset($record['start_time']) ? date('Y-m-d', strtotime($record['start_time'])) : ''?>" />
        </div>

        <div class="form-group">
            <label for="end_time">End time</label>
            <input type="date" name="end_time" id="end_time" class="form-control" value="<?=isset($record['end_time']) ? date('Y-m-d', strtotime($record['end_time'])) : ''?>" />
        </div>

        <fieldset class="form-group">
            <legend><?=__('Classification');?></legend>
            <?php $selectedClassification = formFieldValue('classification', $record); ?>
            <div class="field">
                <select name="classification">
                    <?=selectOptions($classifications, $selectedClassification ?? null, ' - '.__('No classification').' - ');?>
                </select>
            </div>
        </fieldset>

        <fieldset class="form-group">
            <legend><?=__('Operator');?></legend>
			<?php $selectedOperator = formFieldValue('operator', $record); ?>
            <div class="field">
                <select name="operator">
					<?=selectOptions($operators, $selectedOperator ?? null, ' - '.__('No operator').' - ');?>
                </select>
            </div>
        </fieldset>

        <fieldset class="form-group">
            <legend><?=__('Riverbank');?></legend>
			<?php $selectedRiverbank = formFieldValue('riverbank', $record); ?>
            <div class="field">
                <select name="riverbank">
					<?=selectOptions($riverbanks, $selectedRiverbank ?? null, ' - '.__('No riverbank').' - ');?>
                </select>
            </div>
        </fieldset>

        <fieldset class="form-group">
            <legend><?=__('Waterbody');?></legend>
			<?php $selectedWaterbody = formFieldValue('waterbody', $record); ?>
            <div class="field">
                <select name="waterbody">
					<?=selectOptions($waterbodies, $selectedWaterbody ?? null, ' - '.__('No waterbody').' - ');?>
                </select>
            </div>
        </fieldset>

        <fieldset class="form-group">
            <div class="field">
                <legend><?=__('Observed properties');?></legend>
                <select name="observedProperties[]" multiple>
                    <?php foreach ($observedProperties as $id => $symbol): ?>
                        <option value="<?= $id; ?>" <?= isset($record['observedProperties']) && in_array($id, $record['observedProperties']) ? 'selected' : '' ?>><?= $symbol; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </fieldset>

        <div class="field">
            <input type="submit" class="btn btn-primary" value="Save"/>
        </div>
    </form>
</div>

<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
