<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card formPage">
	<?=includeTemplatePart('crud_show_header.phtml', get_defined_vars());?>
	<form action="" novalidate class="needs-validation" method="POST">
        <input type="hidden" name="__csrf" value="<?=$csrf;?>"/>
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" class="form-control <?=isFieldInvalidClass('name', get_defined_vars());?>" required value="<?=formFieldValue('name', $record);?>" />
            <div class="invalid-feedback">
                <?=getFieldInvalidMessage('name', get_defined_vars(), 'Please provide a valid name!');?>
            </div>
        </div>

        <div class="form-group">
            <label for="ncd_wgst">NCD WGST</label>
            <input type="text" name="ncd_wgst" id="ncd_wgst" class="form-control <?=isFieldInvalidClass('ncd_wgst', get_defined_vars());?>" required value="<?=formFieldValue('ncd_wgst', $record);?>" />
            <div class="invalid-feedback">
	            <?=getFieldInvalidMessage('ncd_wgst', get_defined_vars(), 'Please provide a valid Ncd wgst value!');?>
            </div>
        </div>

        <div class="form-check">
			<input type="hidden" name="is_active" value="0"/>
			<input type="checkbox" name="is_active" id="is_active" value="1" class="form-check-input" <?=formFieldValue('is_active', $record) ? 'checked' : '';?>/>
			<label for="is_active">Is active</label>
        </div>

        <div class="form-check">
            <input type="hidden" name="is_out_of_order" value="0"/>
            <input type="checkbox" name="is_out_of_order" id="is_out_of_order" value="1" class="form-check-input" <?=formFieldValue('is_out_of_order', $record) ? 'checked' : '';?>/>
            <label for="is_out_of_order">Is Ouf of Order</label>
        </div>

        <div class="form-group">
            <label for="vertical_reference">Vertical reference</label>
            <input type="text" name="vertical_reference" id="vertical_reference" class="form-control" value="<?=formFieldValue('vertical_reference', $record);?>" />
        </div>

        <div class="form-group">
            <label for="country">Country</label>
            <input type="text" name="country" id="country" maxlength="2" class="form-control <?=isFieldInvalidClass('country', get_defined_vars());?>" value="<?=formFieldValue('country', $record);?>" />
			<div class="invalid-feedback">
		        <?=getFieldInvalidMessage('country', get_defined_vars());?>
			</div>
        </div>

        <div class="form-group">
            <label for="lat">Latitude coordinate</label>
            <input type="number" name="lat" id="lat" step="0.000001" class="form-control" value="<?=formFieldValue('lat', $record);?>" />
        </div>

        <div class="form-group">
            <label for="long">Longitude coordinate</label>
            <input type="number" name="long" id="long" step="0.000001" class="form-control" value="<?=formFieldValue('long', $record);?>" />
        </div>

        <div class="form-group">
            <label for="z">Z coordinate</label>
            <input type="number" name="z" id="z" step="0.000001" class="form-control" value="<?=formFieldValue('z', $record);?>" />
        </div>

        <div class="form-group">
            <label for="location">Location</label>
            <input type="text" name="location" id="location" class="form-control" value="<?=formFieldValue('location', $record);?>" />
        </div>

        <div class="form-group">
            <label for="river_kilometer">River kilometer</label>
            <input type="number" name="river_kilometer" id="river_kilometer" step="0.000001"  class="form-control" value="<?=formFieldValue('river_kilometer', $record);?>" />
        </div>

        <div class="form-group">
            <label for="catchment_area">Catchment area</label>
            <input type="number" name="catchment_area" id="catchment_area" step="0.000001"  class="form-control" value="<?=formFieldValue('catchment_area', $record);?>" />
        </div>

        <div class="form-group">
            <label for="gauge_zero">Gauge zero</label>
            <input type="number" name="gauge_zero" id="gauge_zero" step="0.000001"  class="form-control" value="<?=formFieldValue('gauge_zero', $record);?>" />
        </div>

        <div class="form-group">
            <label for="river_basin">River basin</label>
            <input type="text" name="river_basin" id="river_basin" class="form-control" value="<?=formFieldValue('river_basin', $record);?>" />
        </div>

        <div class="form-group">
            <label for="start_time">Start time</label>
            <input type="date" name="start_time" id="start_time" class="form-control" value="<?=isset($record['start_time']) ? date('Y-m-d', strtotime($record['start_time'])) : ''?>" />
        </div>

        <div class="form-group">
            <label for="end_time">End time</label>
            <input type="date" name="end_time" id="end_time" class="form-control" value="<?=isset($record['end_time']) ? date('Y-m-d', strtotime($record['end_time'])) : ''?>" />
        </div>

        <fieldset class="form-group">
            <legend><?=__('Station classification');?></legend>
            <?php $selectedClassification = formFieldValue('classification', $record); ?>
            <div class="field">
                <select name="classification">
                    <?=selectOptions($classifications, $selectedClassification ?? null, ' - '.__('No classification').' - ');?>
                </select>
            </div>
        </fieldset>

        <fieldset class="form-group">
            <legend><?=__('Operator');?></legend>
			<?php $selectedOperator = formFieldValue('operator', $record); ?>
            <div class="field">
                <select name="operator" class="<?=isFieldInvalidClass('operator', get_defined_vars());?>">
					<?=selectOptions($operators, $selectedOperator ?? null, ' - '.__('No operator').' - ');?>
                </select>
				<div class="invalid-feedback">
		            <?=getFieldInvalidMessage('operator', get_defined_vars());?>
				</div>
            </div>
        </fieldset>

        <fieldset class="form-group">
            <legend><?=__('Riverbank');?></legend>
			<?php $selectedRiverbank = formFieldValue('riverbank', $record); ?>
            <div class="field">
                <select name="riverbank">
					<?=selectOptions($riverbanks, $selectedRiverbank ?? null, ' - '.__('No riverbank').' - ');?>
                </select>
            </div>
        </fieldset>

        <fieldset class="form-group">
            <legend><?=__('River');?></legend>
			<?php $selectedRiver = formFieldValue('river', $record); ?>
            <div class="field">
                <select name="river">
					<?=selectOptions($rivers, $selectedRiver ?? null, ' - '.__('No river').' - ');?>
                </select>
            </div>
        </fieldset>

        <fieldset class="form-group">
            <div class="field">
                <legend><?=__('Observed properties');?></legend>
                <select name="observedProperties[]" multiple>
                    <?php foreach ($observedProperties as $id => $symbol): ?>
                        <option value="<?= $id; ?>" <?= isset($record['observedProperties']) && in_array($id, $record['observedProperties']) ? 'selected' : '' ?>><?= $symbol; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </fieldset>

        <div class="field">
            <input type="submit" class="btn btn-primary" value="Save"/>
        </div>
    </form>
</div>

<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
