<form method="get" class="form-inline filterForm">
	<?php if (isset($listFilters) && !is_null($listFilters)) { ?>
		<?php foreach ($listFilters as $name => $listFilter) { ?>
			<div class="form-group listFilter mr-3">
				<?php if (!empty($listFilter['type']) && $listFilter['type'] === 'date') {?>
					<label for="filter<?=$name;?>"><?=$listFilter['label'];?></label>
					<input type="date" name="<?=$name;?>" id="filter<?=$name;?>" class="form-control form-control-sm" value="<?=$listFilter['selected'] ?? '';?>" />
				<?php } elseif (!empty($listFilter['type']) && $listFilter['type'] === 'hidden') { ?>
					<input type="hidden" name="<?=$name;?>" value="<?=$listFilter['selected'] ?? '';?>" />
				<?php } else { ?>
					<select name="<?=$name;?>" class="form-control form-control-sm">
						<option value=""> - <?=$listFilter['label'];?> - </option>
						<?php foreach ($listFilter['options'] as $value => $label) { ?>
							<option value="<?=$value;?>" <?=(!empty($listFilter['selected']) && $listFilter['selected'] == $value) ? 'selected' : '';?>>
								<?=$label;?>
							</option>
						<?php } ?>
					</select>
				<?php } ?>
			</div>
		<?php } ?>
	<?php } ?>
	<div class="form-group listSearch mr-3">
		<input type="search" name="search" class="form-control form-control-sm" placeholder="<?=__('Search')?>" value="<?=htmlspecialchars(urldecode($searchString))?>">
	</div>
	<div class="form-group filterSubmit">
		<?php if (getCurrentOrderBy()) {?>
			<input type="hidden" name="order_by" value="<?=getCurrentOrderBy();?>" />
		<?php } ?>
		<?php if (getCurrentOrderDir()) {?>
			<input type="hidden" name="order_dir" value="<?=getCurrentOrderDir();?>" />
		<?php } ?>
		<input type="submit" class="btn btn-sm btn-primary mr-2" value="<?=__('Filter');?>"/>
		<input type="reset" class="btn btn-sm btn-secondary" value="<?=__('Clear');?>"/>
	</div>
</form>