<?php include __DIR__ . '../../layouts/before_app.phtml'; ?>

	<div class="card formPage accessRules">
		<?=includeTemplatePart('crud_show_header.phtml', get_defined_vars());?>
		<form action="" method="POST" id="accessRuleForm">
			<input type="hidden" name="__csrf" value="<?=$csrf;?>"/>

            <fieldset class="form-group">
                <div class="field">
                    <legend><?=__('Operator');?></legend>
                    <select name="operator" id="accessRuleOperatorSelect">
						<?=selectOptions($operators, $record['operator_id'] ?? null);?>
                    </select>
	                <div class="invalid-feedback">
		                <?=getFieldInvalidMessage('operator', get_defined_vars());?>
	                </div>
                </div>
            </fieldset>

			<div class="form-group" id="pointSelect">
				<div class="field">
					<label for="monitoringpoint_selector">Monitoring point selector</label>
					<select name="monitoringpoint_selector[]" id="accessRulePointSelect"
					        class="<?=isFieldInvalidClass('monitoringpoint_selector', get_defined_vars());?>"
							data-ajaxdefault="/admin/ajax/select/operator-points"
							data-ajax="/admin/ajax/select/operator-points"
							data-value="<?=formFieldValue('monitoringpoint_selector', $record);?>" multiple></select>
					<div class="invalid-feedback">
						<?=getFieldInvalidMessage('monitoringpoint_selector', get_defined_vars());?>
					</div>
				</div>
			</div>

            <div class="form-group" id="propertySelect">
                <label for="observed_property_selector">Observed property selector</label>
				<select name="observed_property_selector[]" id="accessRulePropertySelect"
				        class="<?=isFieldInvalidClass('observed_property_selector', get_defined_vars());?>"
						data-ajaxdefault="/admin/ajax/select/operator-properties"
						data-ajax="/admin/ajax/select/operator-properties"
						data-value="<?=formFieldValue('observed_property_selector', $record);?>"
						multiple></select>
	            <div class="invalid-feedback">
		            <?=getFieldInvalidMessage('observed_property_selector', get_defined_vars());?>
	            </div>
            </div>

            <fieldset class="form-group">
                <div class="field">
                    <legend><?=__('Groups');?></legend>
                    <select name="groups[]"
                            class="<?=isFieldInvalidClass('groups', get_defined_vars());?>"
                            multiple>
						<?php foreach ($groups as $id => $name): ?>
                            <option value="<?= $id; ?>" <?= isset($record['groups']) && in_array($id, formFieldValue('groups', $record)) ? 'selected' : '' ?>>
	                            <?= $name; ?>
                            </option>
						<?php endforeach; ?>
                    </select>
	                <div class="invalid-feedback">
		                <?=getFieldInvalidMessage('groups', get_defined_vars());?>
	                </div>
                </div>
            </fieldset>

            <fieldset class="form-group">
                <h4>Time interval</h4>
	            <?php if(isFieldInvalidClass('intervals', get_defined_vars())) { ?>
		            <div class="invalid-feedback" style="display: inline-block">
			            <?=getFieldInvalidMessage('intervals', get_defined_vars());?>
		            </div>
				<?php } ?>


                <div class="form-group">
                    <label for="interval_years">Years</label>
                    <input type="number" name="interval_years" id="interval_years" class="form-control <?=isFieldInvalidClass('interval_years', get_defined_vars());?>"
						   value="<?=(!empty($_POST) && $_POST['interval_years']) ? $_POST['interval_years'] : (isset($record['interval']) ? (new DateInterval($record['interval']))->y : '') ?>" />
	                <div class="invalid-feedback">
		                <?=getFieldInvalidMessage('interval_years', get_defined_vars());?>
	                </div>
                </div>

                <div class="form-group">
                    <label for="interval_months">Months</label>
                    <input type="number" name="interval_months" id="interval_months" class="form-control <?=isFieldInvalidClass('interval_months', get_defined_vars());?>"
                           value="<?=(!empty($_POST) && $_POST['interval_months']) ? $_POST['interval_months'] : (isset($record['interval']) ? (new DateInterval($record['interval']))->m : '') ?>" />
	                <div class="invalid-feedback">
		                <?=getFieldInvalidMessage('interval_months', get_defined_vars());?>
	                </div>
                </div>

                <div class="form-group">
                    <label for="interval_days">Days</label>
                    <input type="number" name="interval_days" id="interval_days" class="form-control <?=isFieldInvalidClass('interval_days', get_defined_vars());?>"
						   value="<?=(!empty($_POST) && $_POST['interval_days']) ? $_POST['interval_days'] : (isset($record['interval']) ? (new DateInterval($record['interval']))->d : '') ?>" />
	                <div class="invalid-feedback">
		                <?=getFieldInvalidMessage('interval_days', get_defined_vars());?>
	                </div>
                </div>
            </fieldset>
            <div class="field">
				<input type="submit" class="btn btn-primary" value="Save"/>
			</div>
		</form>
	</div>

<?php include __DIR__ . '../../layouts/after_app.phtml'; ?>