<?php include __DIR__ . '../../../layouts/before_app.phtml'; ?>
<div class="card showPage">
	<div class="actions">
		<a href="/admin/hydro/riverbanks/edit?id=<?=$record['id'];?>" class="btn btn-primary">Edit riverbank</a>
		<a href="<?=$listPage;?>" class="btn btn-secondary">Back to list</a>
	</div>

	<h1>Hydro riverbank #<?=$record['id'] ?? '';?></h1>

    <dl class="row">
        <dt class="col-sm-5">ID</dt>
        <dd class="col-sm-7">#<?=$record['id'] ?? '';?></dd>
        <dt class="col-sm-5">Value</dt>
        <dd class="col-sm-7"><?=$record['value'] ?? '';?></dd>
    </dl>
</div>
<?php include __DIR__ . '../../../layouts/after_app.phtml'; ?>
